version: '3'
services:
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=production
      - BASE_URL=/Jotys
    networks:
      - app-network

  backend:
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    networks:
      - app-network

  nginx:
    image: nginx:latest
    ports:
      - "80:80"  # Pastikan Nginx berjalan di port 80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network
    environment:
      - SUBDOMAIN=Jotys

networks:
  app-network:
    driver: bridge
